version: "3"

services:
  nest:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    network_mode: host

    # networks:
    #   - my-network
    volumes:
      - ./src:/app/src
    depends_on:
      - db

  db:
    image: postgres
    network_mode: host

    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bycoders
    # networks:
    #   - my-network

networks:
  my-network:
    driver: bridge