version: "3"
services:
  nest:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /home/josesantos/bycoders/api/src
    depends_on:
      - db
      - rabbitmq
  db:
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
  rabbitmq:
    image: rabbitmq
