# Escolha uma imagem base do Node.js
FROM node:14

# Define o diretório de trabalho
WORKDIR /usr/src/

# Copia os arquivos de configuração
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia o código fonte da aplicação
COPY . .

# Expõe a porta em que a aplicação estará rodando
EXPOSE 3000

# Comando para iniciar a aplicação
CMD [ "npm", "start" ]
